version: "3"
services:
  spring-boot-app:
    image: spring-boot-docker-app
    #    restart: always
    build:
      context: ./
    ports:
      -  "8080:8080"
    environment:
      - jdbc:mysql://mysqldb:3306/employeedb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb
      - rabbitmq

  mysqldb:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  spring-mysql-net:
volumes:
  mysql-data: