spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  datasource:
    url: jdbc:mysql://mysqldb:3306/employeedb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          show-sql: true
          format-sql: true
      hibernate:
        ddl-auto: update

rabbit:
  topic-exchange-name: spring-boot-exchange
  queue-name: spring-boot
  routing-key: foo.bar.baz
