spring:
  rabbitmq:
    host: rabbitmq
  datasource:
    url: jdbc:mysql://mysqldb:3306/employeedb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: false
#      properties:
#        hibernate.id.new_generator_mappings: true
#        hibernate.cache.use_second_level_cache: true
#        hibernate.cache.use_query_cache: false
#        hibernate.generate_statistics: false
rabbit:
  topic-exchange-name: spring-boot-exchange
  queue-name: spring-boot
  routing-key: foo.bar.baz
